config/routes.rb
Rails.application.routes.draw do
  resources :foods
  devise_for :users
  root 'home#index'

  get 'home/about'

end

app/models/food.rb
class Food < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  respond_to :html
  # GET /foods
  # GET /foods.json
  def index
     @foods = Food.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    respond_with(@food)
  end

  # GET /foods/new
  def new
    @food = current_user.foods.build
  end

  # GET /foods/1/edit
  def edit
     respond_with(@food)
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = current_user.foods.build(food_params)
    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
   end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name,:image, :description, :price)
    end

  def correct_user
      @food = current_user.foods.find_by(id: params[:id])
     redirect_to foods_path, notice: "Not authorized to edit this food" if @food.nil?
   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/foods/_form.html.erb
<%= form_for @food, html: { multipart: true } do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
   
<div class="container">
   <div id="foods" class="transitions-enabled">
   <% @foods.each do |food| %>
     <div class="box">
       <div class="panel panel-default">
       <%= link_to image_tag(food.image.url(:medium)), food %><br/>
         <div class="panel-body">
         <%= food.name %><br/>
         <td><%= link_to 'Show Detail...', food %></td>

        </div>
         <% if food.user == current_user %>
         <div class="panel-footer">
         <%= link_to 'Edit', edit_food_path(food) %><br/>
         <%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you
         sure?' } %>
         </div>
         <% end %>
       </div>
     </div>
     <% end %>
   </div>
</div>

 <div class="center"> 
     <%= will_paginate @foods, renderer: BootstrapPagination::Rails %>
 </div>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<div class="row">
<div class="col-md-offset-2 col-md-8">

<div class="panel panel-default">
<div class="panel-heading center"><%= image_tag @food.image.url(:medium) %></div>
	 <div class="panel-body">
	 <%= @food.description %><br/>
	 <%= @food.name %><br/>
 	 <%= @food.price %><br/>

	<% if @food.user == current_user %>
		<%= link_to 'Edit', edit_food_path(@food) %> |
	 <% end %>
	<%= link_to 'Back', foods_path %>
 </div>
</div>
</div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
   <div class="container">
 	<!-- Brand and toggle get grouped for better mobile display -->
 	<div class="navbar-header">
 	  <button type="button" class="navbar-toggle collapsed" data-
 
 	   toggle="collapse" data-target="#bs-example-navbar-collapse-1">
 		   <span class="sr-only">Toggle navigation</span>
 		   <span class="icon-bar"></span>
 		   <span class="icon-bar"></span>
 		  <span class="icon-bar"></span>
 	  </button>
 	  <%= link_to 'FoodLover', root_path, class: 'navbar-brand' %>
 	</div>

 <!-- Collect the nav links, forms, and other content for toggling -->
 	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 		<ul class="nav navbar-nav navbar-right">
 			<li><%= link_to 'Home', root_path %></li>
 			<li><%= link_to 'About Me', home_about_path %></li>
 			</li>
 			<li><%= link_to 'List Foods', foods_path %></li>
 			<li><%= link_to 'Add Food', new_food_path %></li>
 			<% if user_signed_in? %>
 				<li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
 				<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
 						<% else %>
 				<li><%= link_to "Login", new_user_session_path %></li>
 				
 				<li><%= link_to "Join", new_user_registration_path %></li>
 			<% end %>
 		</ul>
 	</div><!-- /.navbar-collapse -->
 	</div><!-- /.container-fluid -->
 </nav>

app/views/home/about.html.erb
<div class="jumbotron">
	<h1>About Me...</h1>
	<p>My name Is sondg and I'm Building a Pinterest Clone</p>
	<%= link_to 'Home', root_path, class: 'btn btn-primary' %>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
	<h1>Welcome to FoodLover</h1>
	<p>FoodLover</p>
	<%= link_to 'About Us', home_about_path, class: 'btn btn-default' %>
	<%= link_to 'Home', root_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FOODLOVER</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
<%= render 'home/header' %>

<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
 	<% end %>
	<%= yield %>
</div>

</body>
</html>